pipeline {
    agent { label 'AGENT-1'}
    environment {
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = ''
        ACC_ID = '090808669085'
    }
    options {
        disableConcurrentBuilds ()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }

    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan
                        """
                    }
                }
            }
        } 
        stage('Apply') {
            input {
                message "Deploy to production?"
                ok "Deploy."
            }
            steps {
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                        cd 10-sg
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Parallel Stages') {
            parallel {
                stage ('20-bastion') {
                    steps {
                        script{
                            sh """
                                Hello, This is stage 20-bastion
                                sleep 10
                            """
                            }
                        }
                    }
                stage ('30-rds') {
                    steps {
                        script{
                            sh """
                                Hello, This is stage 30-rds
                                sleep 10
                            """
                            }
                        }
                    }
                    
                stage ('40-eks') {
                    steps {
                        script{
                            sh """
                                Hello, This is stage 40-eks
                                sleep 10
                            """
                            }
                        }
                    }
                stage ('50-ecr') {
                    steps {
                        script{
                            sh """
                                Hello, This is stage 50-ecr
                                sleep 10
                            """
                            }
                        }
                    }
                }
            }      
            
    }
        
    post {
        always {
            echo "I will always say hello-again"
            deleteDir()
        }
        failure {
            echo "I will run when pipeline fails"
        }
        success {
            echo "I will run when pipeline succeeds"
        }
    }
}